openapi: "3.0.0"
info:
  title: "Device Data Collection System"
  version: "1.0.0"
paths:
  /auth/google:
    get:
      summary: "Initiates Google OAuth authentication"
      responses:
        '302':
          description: "Redirect to Google OAuth"
  /auth/google/callback:
    get:
      summary: "Handles Google OAuth callback"
      parameters:
        - name: code
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Authentication successful"
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: "Invalid Google token"
        '500':
          description: "Authentication failed"